[package]
name = "ed25519-dalek"
version = "1.0.0-pre.3"
edition = "2018"
authors = ["isis lovecruft <isis@patternsinthevoid.net>"]
readme = "README.md"
license = "BSD-3-Clause"
repository = "https://github.com/dalek-cryptography/ed25519-dalek"
homepage = "https://dalek.rs"
documentation = "https://docs.rs/ed25519-dalek"
keywords = ["cryptography", "ed25519", "curve25519", "signature", "ECC"]
categories = ["cryptography", "no-std"]
description = "Fast and efficient ed25519 EdDSA key generations, signing, and verification in pure Rust."
exclude = [ ".gitignore", "TESTVECTORS", "res/*" ]

[badges]
travis-ci = { repository = "dalek-cryptography/ed25519-dalek", branch = "master"}

[package.metadata.docs.rs]
# Disabled for now since this is borked; tracking https://github.com/rust-lang/docs.rs/issues/302
# rustdoc-args = ["--html-in-header", ".cargo/registry/src/github.com-1ecc6299db9ec823/curve25519-dalek-0.13.2/rustdoc-include-katex-header.html"]
features = ["nightly", "batch"]

[dependencies]
eddsa-dalek = { path = "../eddsa-dalek", default-features = false }
sha2 = { version = "0.8", default-features = false }

[dev-dependencies]
hex = "^0.4"
bincode = "^0.9"
criterion = "0.3"
rand = "0.7"
dev-serde = { version = "1.0", package = "serde" }

[[bench]]
name = "ed25519_benchmarks"
harness = false
# This doesn't seem to work with criterion, cf. https://github.com/bheisler/criterion.rs/issues/344
# For now, we have to bench by doing `cargo bench --features="batch"`.
# required-features = ["batch"]

[features]
default = ["std", "u64_backend"]
std = ["eddsa-dalek/std", "sha2/std"]
alloc = ["eddsa-dalek/alloc"]
nightly = ["eddsa-dalek/nightly"]
serde = ["eddsa-dalek/serde"]
batch = ["eddsa-dalek/batch"]
batch_deterministic = ["eddsa-dalek/batch_deterministic"]
asm = ["sha2/asm"]
legacy_compatibility = ["eddsa-dalek/legacy_compatibility"]
u64_backend = ["eddsa-dalek/u64_backend"]
u32_backend = ["eddsa-dalek/u32_backend"]
simd_backend = ["eddsa-dalek/simd_backend"]
